# Generated by Django 3.0.7 on 2020-06-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, default='', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default='', max_digits=9)),
                ('tags', models.ManyToManyField(to='IReporter.Tag')),
            ],
            options={
                'verbose_name_plural': 'Flags',
            },
        ),
    ]
