# Generated by Django 3.0.7 on 2020-06-21 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IReporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionrecord',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IReporter.Profile'),
        ),
    ]
