# Generated by Django 3.0.7 on 2020-06-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionrecord',
            name='status',
            field=models.CharField(choices=[('Under Investigation', 'Under Investigation'), ('rejected', 'rejected'), ('resolved', 'resolved')], default='', max_length=250),
        ),
    ]
