# Generated by Django 3.0.7 on 2020-06-18 16:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IReporter', '0002_auto_20200618_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='picture'),
        ),
        migrations.DeleteModel(
            name='ProfilePic',
        ),
    ]
