# Generated by Django 3.0.7 on 2020-06-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReporter', '0003_auto_20200619_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('Under Investigation', 'Under Investigation'), ('rejected', 'rejected'), ('resolved', 'resolved')], default='', max_length=250),
        ),
    ]
