# Generated by Django 3.0.7 on 2020-06-19 16:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IReporter', '0005_auto_20200619_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionrecord',
            name='videos',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='interventionvideos'),
        ),
    ]
