# Generated by Django 3.0.7 on 2020-06-20 03:03

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReporter', '0006_interventionrecord_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionrecord',
            name='videos',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
