# Generated by Django 3.0.7 on 2020-06-20 03:34

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReporter', '0007_auto_20200620_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionrecord',
            name='image',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/interventionimages/'),
        ),
        migrations.AlterField(
            model_name='interventionrecord',
            name='videos',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
